### ISSUE TITLE
EnvironmentError: The CUDA lib64 path could not be located in /usr/lib64

### ISSUE THREAD

**Issue by WuZhuoran** [Guanghan/lighttrack#1]
Error occured during `make`.

```
#python3.5 setup.py build_ext --inplace
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 52, in locate_cuda
    raise EnvironmentError('The CUDA %s path could not be located in %s' % (k, v))
EnvironmentError: The CUDA lib64 path could not be located in /usr/lib64
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by WuZhuoran** [comment]
This can be solved by change `setup.py`

From

```
cudaconfig = {'home':home, 'nvcc':nvcc,
                  'include': pjoin(home, 'include'),
                  'lib64': pjoin(home, 'lib64')}
```

To

```
cudaconfig = {'home':home, 'nvcc':nvcc,
                  'include': pjoin(home, 'include'),
                  'lib64': pjoin(home, 'lib')}
```
