### ISSUE TITLE
while running demo_video_mobile.py, I came across this problem.

### ISSUE THREAD

**Issue by xiong-peng** [Guanghan/lighttrack#32]
Detector YOLOv3 options: Namespace(batch_size=1, checkpoint_model=None, conf_thres=0.8, config_path='detector/config/yolov3.cfg', img_size=416, n_cpu=8, nms_thres=0.4, weights_path='weights/YOLOv3/yolov3.weights')
PoseTrack order.
/home/vdai/peng/code/lighttrack-master/graph/gcn_utils/io.py:43: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  default_arg = yaml.load(f)
[08.14.19|11:47:23] Load weights from ./weights/GCN/epoch210_model.pt.
[08.14.19|11:47:23] Load weights [A].
[08.14.19|11:47:23] Load weights [data_bn.weight].
[08.14.19|11:47:23] Load weights [data_bn.bias].
[08.14.19|11:47:23] Load weights [data_bn.running_mean].
[08.14.19|11:47:23] Load weights [data_bn.running_var].
[08.14.19|11:47:23] Load weights [data_bn.num_batches_tracked].
[08.14.19|11:47:23] Load weights [st_gcn_networks.0.gcn.conv.weight].
[08.14.19|11:47:23] Load weights [st_gcn_networks.0.gcn.conv.bias].
[08.14.19|11:47:23] Load weights [st_gcn_networks.1.gcn.conv.weight].
[08.14.19|11:47:23] Load weights [st_gcn_networks.1.gcn.conv.bias].
[08.14.19|11:47:23] Load weights [edge_importance.0].
[08.14.19|11:47:23] Load weights [edge_importance.1].
[08.14.19|11:47:23] Load weights [fcn.weight].
[08.14.19|11:47:23] Load weights [fcn.bias].
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torchlight-1.0-py3.5.egg/torchlight/io.py", line 82, in load_weights
    __doc__ = _io._TextIOBase.__doc__
  File "/home/vdai/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "data_bn.num_batches_tracked". 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vdai/peng/code/lighttrack-master/demo_video_mobile.py", line 32, in <module>
    from graph import visualize_pose_matching
  File "/home/vdai/peng/code/lighttrack-master/graph/visualize_pose_matching.py", line 297, in <module>
    pose_matcher = Pose_Matcher()
  File "/home/vdai/peng/code/lighttrack-master/graph/visualize_pose_matching.py", line 162, in __init__
    self.load_weights()
  File "/home/vdai/peng/code/lighttrack-master/graph/gcn_utils/io.py", line 79, in load_weights
    self.arg.ignore_weights)
  File "/usr/local/lib/python3.5/dist-packages/torchlight-1.0-py3.5.egg/torchlight/io.py", line 89, in load_weights
    
  File "/home/vdai/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "data_bn.num_batches_tracked".

**Comment by JosePeeterson** [comment]
Hi,
could you please share your env dependencies file with all the version numbers? and the cuda toolkit version.

When you first ran demo_video_mobile.py did you see the following error?
`
Traceback (most recent call last): File "demo_video_mobile.py", line 28, in <module> from nms.gpu_nms import gpu_nms ImportError: /home/peeterson/Desktop/lighttrack/HPE/../lib/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
`

If you did could you share how you solved it? thanks.
