### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zfyong** [Guanghan/lighttrack#7]
I just perform LightTrack demo on my own video, and yolov3 detects nothing in one frame, then this problem appear.
![image](https://user-images.githubusercontent.com/47889983/57593470-1d4dc880-756e-11e9-8ae0-128e4c579537.png)

**Comment by Guanghan** [comment]
@zfyong 
Hi zfyong, I have tried with a blackscreen video where 0 candidates are detected for each frame, but nothing is wrong (No "IndexError: list index out of range"). Could you print the error messages? Or can you provide the video so I can repeat the problem? Thanks!

**Comment by Guanghan** [comment]
@zfyong Resolved and closed.

**Comment by zfyong** [comment]
```
Detector YOLOv3 options: Namespace(batch_size=1, checkpoint_model=None, conf_thres=0.8, config_path='detector/config/yolov3.cfg', img_size=416, n_cpu=8, nms_thres=0.4, weights_path='weights/YOLOv3/yolov3.weights')
PoseTrack order.
[05.14.19|11:28:13] Load weights from ./weights/GCN/epoch210_model.pt.
[05.14.19|11:28:13] Load weights [A].
[05.14.19|11:28:13] Load weights [data_bn.weight].
[05.14.19|11:28:13] Load weights [data_bn.bias].
[05.14.19|11:28:13] Load weights [data_bn.running_mean].
[05.14.19|11:28:13] Load weights [data_bn.running_var].
[05.14.19|11:28:13] Load weights [data_bn.num_batches_tracked].
[05.14.19|11:28:13] Load weights [st_gcn_networks.0.gcn.conv.weight].
[05.14.19|11:28:13] Load weights [st_gcn_networks.0.gcn.conv.bias].
[05.14.19|11:28:13] Load weights [st_gcn_networks.1.gcn.conv.weight].
[05.14.19|11:28:13] Load weights [st_gcn_networks.1.gcn.conv.bias].
[05.14.19|11:28:13] Load weights [edge_importance.0].
[05.14.19|11:28:13] Load weights [edge_importance.1].
[05.14.19|11:28:13] Load weights [fcn.weight].
[05.14.19|11:28:13] Load weights [fcn.bias].
2019-05-14 11:28:13.645323: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-14 11:28:13.651613: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-05-14 11:28:13.652037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 9.40GiB
2019-05-14 11:28:13.652049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-05-14 11:28:14.643305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-14 11:28:14.643331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-05-14 11:28:14.643338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-05-14 11:28:14.643609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9089 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
05-14 11:28:14 Generating testing graph on 1 GPUs ...
05-14 11:28:14 Initialized model weights from weights/mobile-deconv/snapshot_296.ckpt ...
2019-05-14 11:28:15.100904: W tensorflow/core/framework/allocator.cc:122] Allocation of 16777216 exceeds 10% of system memory.
05-14 11:28:15 Current epoch is 296.
unknown error reading video file
/home/zhifan/MachineLearning/poses/lighttrack/data/demo
2.mp4
Current tracking: [image_id:0]
Keyframe: 4 detections
Current tracking: [image_id:1]
Current tracking: [image_id:2]
Current tracking: [image_id:3]
Current tracking: [image_id:4]
Current tracking: [image_id:5]
Current tracking: [image_id:6]
Current tracking: [image_id:7]
Current tracking: [image_id:8]
Current tracking: [image_id:9]
Current tracking: [image_id:10]
Keyframe: 4 detections
Current tracking: [image_id:11]
Current tracking: [image_id:12]
Current tracking: [image_id:13]
Current tracking: [image_id:14]
Current tracking: [image_id:15]
Current tracking: [image_id:16]
Current tracking: [image_id:17]
Current tracking: [image_id:18]
Current tracking: [image_id:19]
Current tracking: [image_id:20]
Keyframe: 4 detections
Current tracking: [image_id:21]
Current tracking: [image_id:22]
Current tracking: [image_id:23]
Current tracking: [image_id:24]
Current tracking: [image_id:25]
Current tracking: [image_id:26]
Current tracking: [image_id:27]
Current tracking: [image_id:28]
Current tracking: [image_id:29]
Current tracking: [image_id:30]
Keyframe: 0 detections
Current tracking: [image_id:31]
Current tracking: [image_id:32]
Keyframe: 4 detections
Traceback (most recent call last):
  File "demo_video_mobile.py", line 746, in <module>
    visualize_folder, output_video_path)
  File "demo_video_mobile.py", line 160, in light_track
    track_id = get_track_id_SpatialConsistency(bbox_gt, bbox_dets_list_list, img_id)
  File "demo_video_mobile.py", line 329, in get_track_id_SpatialConsistency
    bbox_dets_list = bbox_dets_list_list[img_id - 1]
IndexError: list index out of range
```
video path: https://pan.baidu.com/s/18fsDIICc6kiiuGBKOZ4MRw
password: 7g3p

**Comment by Guanghan** [comment]
@zfyong Yes, this indeed is a problem. I updated this today. Please try the latest demo_video_mobile.py, it should resolve this issue.

**Comment by zfyong** [comment]
Great! thank you.
